[package]
name = "rustenium"
version = "0.1.0"
edition = "2021"

[dependencies]
rustenium-core = { path = "../rustenium-core" }
rustenium-bidi-commands = { path = "../rustenium-bidi-commands"}
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
reqwest = { version = "0.12.15", features = ["json"] }
thiserror = "2.0.17"